### ISSUE TITLE
Improve event metadata structure

### ISSUE THREAD

**Issue by bernhold** [ideas-productivity/ideas-productivity.github.io#60]
We should probably take advantage of the nesting possible with YAML.

Instead of `venue`, `venue-type`, `venue-url`, and `location`, we could have
```
venue:
  name:
  type:
  url:
  location:
```

And similarly for `parent-event`,  and maybe others.
